apiVersion: v1
kind: Secret
metadata:
  name: aegis-secrets
  namespace: aegis-system
  labels:
    app.kubernetes.io/name: aegis-secrets
    app.kubernetes.io/part-of: aegis-reliability-platform
type: Opaque
stringData:
  POSTGRES_USER: "aegis"
  POSTGRES_PASSWORD: "aegis_secure_password"
  DATABASE_URL: "postgresql+asyncpg://aegis:aegis_secure_password@aegis-postgres-service:5432/aegisai"
  DATABASE_SYNC_URL: "postgresql://aegis:aegis_secure_password@aegis-postgres-service:5432/aegisai"
  OPERATOR_SIGNING_KEY: "aegis_super_secure_operator_signing_key_2026"
