apiVersion: v1
kind: Service
metadata:
  name: aegis-api-service
  namespace: aegis-system
  labels:
    app: aegis-api
    app.kubernetes.io/name: aegis-api-service
    app.kubernetes.io/part-of: aegis-reliability-platform
spec:
  type: ClusterIP
  selector:
    app: aegis-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: aegis-postgres-service
  namespace: aegis-system
  labels:
    app: aegis-postgres
    app.kubernetes.io/name: aegis-postgres-service
    app.kubernetes.io/part-of: aegis-reliability-platform
spec:
  type: ClusterIP
  selector:
    app: aegis-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: aegis-redis-service
  namespace: aegis-system
  labels:
    app: aegis-redis
    app.kubernetes.io/name: aegis-redis-service
    app.kubernetes.io/part-of: aegis-reliability-platform
spec:
  type: ClusterIP
  selector:
    app: aegis-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: aegis-mlflow-service
  namespace: aegis-system
  labels:
    app: aegis-mlflow
    app.kubernetes.io/name: aegis-mlflow-service
    app.kubernetes.io/part-of: aegis-reliability-platform
spec:
  type: ClusterIP
  selector:
    app: aegis-mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
